### ISSUE TITLE
Leer un número entero y determinar cuántos dígitos tiene

### ISSUE THREAD

**Issue by alexpuello09** [alexpuello09/donkie#1]

**Comment by alexpuello09** [comment]
@alexpuello09  porque se divide por 10 en solución

**Comment by alexpuello09** [comment]
Se divide entre 10 porque al dividir en vez de mostrarse el resultado completo se muestra la parte residual ósea el residuo de la división del numero EJEMPLO : 94/10 = 9.4 y si vemos que este resultado es un numero decimal por lo que estamos trabajando con aritmética entera y en aritmética entera no se permiten números decimales

**Comment by spuello** [comment]
@alexpuello09  Muy bien por esa parte, la aritmética. ¿Cómo esa lógica nos sirve para saber la cantidad de dígitos en un número entero?

Porque la división debe ser 10 y no otro número.
